[package]
name = "wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
core = { path = "../core" }
image = "0.24.7"
base64 = "0.21.2"
anyhow = "1.0.68"
serde_json = "1.0.105"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
